# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.RemoveField(
            model_name='label',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
